artist:
  name: starphee.com
  tagline: -The ğ•Œğ•ƒğ•‹ğ•€ğ•„ğ”¸ğ•‹ğ”¼ website-
  # seo_title:
  # seo_description: Play games, check my socials, download files, and more!
  # contact_twitter_username:
  # contact_phone:
  # contact_email:

site_language: en
